/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as authCallbackImport } from "./routes/(auth)/callback";
import { Route as authLoginImport } from "./routes/(auth)/login";
import { Route as authRegisterImport } from "./routes/(auth)/register";
import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes/index";
import { Route as OnboardingSlugImport } from "./routes/onboarding/$slug";
import { Route as OnboardingIndexImport } from "./routes/onboarding/index";
import { Route as ProblemsProblemSlugImport } from "./routes/problems/$problem-slug";
import { Route as ProblemsLayoutImport } from "./routes/problems/_layout";
import { Route as ProblemsLayoutIndexImport } from "./routes/problems/_layout.index";
import { Route as ProblemsIndexImport } from "./routes/problems/index";
import { Route as ProblemsLayoutImport } from "./routes/problems/layout";
import { Route as WaitlistImport } from "./routes/waitlist";

// Create Virtual Routes

const ProblemsImport = createFileRoute("/problems")();

// Create/Update Routes

const ProblemsRoute = ProblemsImport.update({
	path: "/problems",
	getParentRoute: () => rootRoute,
} as any);

const WaitlistRoute = WaitlistImport.update({
	path: "/waitlist",
	getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
	path: "/",
	getParentRoute: () => rootRoute,
} as any);

const ProblemsIndexRoute = ProblemsIndexImport.update({
	path: "/",
	getParentRoute: () => ProblemsRoute,
} as any);

const OnboardingIndexRoute = OnboardingIndexImport.update({
	path: "/onboarding/",
	getParentRoute: () => rootRoute,
} as any);

const ProblemsLayoutRoute = ProblemsLayoutImport.update({
	id: "/_layout",
	getParentRoute: () => ProblemsRoute,
} as any);

const ProblemsProblemSlugRoute = ProblemsProblemSlugImport.update({
	path: "/problems/$problem-slug",
	getParentRoute: () => rootRoute,
} as any);

const OnboardingSlugRoute = OnboardingSlugImport.update({
	path: "/onboarding/$slug",
	getParentRoute: () => rootRoute,
} as any);

const authRegisterRoute = authRegisterImport.update({
	path: "/register",
	getParentRoute: () => rootRoute,
} as any);

const authLoginRoute = authLoginImport.update({
	path: "/login",
	getParentRoute: () => rootRoute,
} as any);

const authCallbackRoute = authCallbackImport.update({
	path: "/callback",
	getParentRoute: () => rootRoute,
} as any);

const ProblemsLayoutIndexRoute = ProblemsLayoutIndexImport.update({
	path: "/",
	getParentRoute: () => ProblemsLayoutRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/": {
			id: "/";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof IndexImport;
			parentRoute: typeof rootRoute;
		};
		"/waitlist": {
			id: "/waitlist";
			path: "/waitlist";
			fullPath: "/waitlist";
			preLoaderRoute: typeof WaitlistImport;
			parentRoute: typeof rootRoute;
		};
		"/(auth)/callback": {
			id: "/callback";
			path: "/callback";
			fullPath: "/callback";
			preLoaderRoute: typeof authCallbackImport;
			parentRoute: typeof rootRoute;
		};
		"/(auth)/login": {
			id: "/login";
			path: "/login";
			fullPath: "/login";
			preLoaderRoute: typeof authLoginImport;
			parentRoute: typeof rootRoute;
		};
		"/(auth)/register": {
			id: "/register";
			path: "/register";
			fullPath: "/register";
			preLoaderRoute: typeof authRegisterImport;
			parentRoute: typeof rootRoute;
		};
		"/onboarding/$slug": {
			id: "/onboarding/$slug";
			path: "/onboarding/$slug";
			fullPath: "/onboarding/$slug";
			preLoaderRoute: typeof OnboardingSlugImport;
			parentRoute: typeof rootRoute;
		};
		"/problems/$problem-slug": {
			id: "/problems/$problem-slug";
			path: "/problems/$problem-slug";
			fullPath: "/problems/$problem-slug";
			preLoaderRoute: typeof ProblemsProblemSlugImport;
			parentRoute: typeof rootRoute;
		};
		"/problems": {
			id: "/problems";
			path: "/problems";
			fullPath: "/problems";
			preLoaderRoute: typeof ProblemsImport;
			parentRoute: typeof rootRoute;
		};
		"/problems/_layout": {
			id: "/problems/_layout";
			path: "/problems";
			fullPath: "/problems";
			preLoaderRoute: typeof ProblemsLayoutImport;
			parentRoute: typeof ProblemsRoute;
		};
		"/problems/layout": {
			id: "/problems/layout";
			path: "/layout";
			fullPath: "/problems/layout";
			preLoaderRoute: typeof ProblemsLayoutImport;
			parentRoute: typeof ProblemsImport;
		};
		"/onboarding/": {
			id: "/onboarding/";
			path: "/onboarding";
			fullPath: "/onboarding";
			preLoaderRoute: typeof OnboardingIndexImport;
			parentRoute: typeof rootRoute;
		};
		"/problems/": {
			id: "/problems/";
			path: "/";
			fullPath: "/problems/";
			preLoaderRoute: typeof ProblemsIndexImport;
			parentRoute: typeof ProblemsImport;
		};
		"/problems/_layout/": {
			id: "/problems/_layout/";
			path: "/";
			fullPath: "/problems/";
			preLoaderRoute: typeof ProblemsLayoutIndexImport;
			parentRoute: typeof ProblemsLayoutImport;
		};
	}
}

// Create and export the route tree

interface ProblemsLayoutRouteChildren {
	ProblemsLayoutIndexRoute: typeof ProblemsLayoutIndexRoute;
}

const ProblemsLayoutRouteChildren: ProblemsLayoutRouteChildren = {
	ProblemsLayoutIndexRoute: ProblemsLayoutIndexRoute,
};

const ProblemsLayoutRouteWithChildren = ProblemsLayoutRoute._addFileChildren(
	ProblemsLayoutRouteChildren,
);

interface ProblemsRouteChildren {
	ProblemsLayoutRoute: typeof ProblemsLayoutRouteWithChildren;
	ProblemsLayoutRoute: typeof ProblemsLayoutRoute;
	ProblemsIndexRoute: typeof ProblemsIndexRoute;
}

const ProblemsRouteChildren: ProblemsRouteChildren = {
	ProblemsLayoutRoute: ProblemsLayoutRoute,
	ProblemsIndexRoute: ProblemsIndexRoute,
};

const ProblemsRouteWithChildren = ProblemsRoute._addFileChildren(
	ProblemsRouteChildren,
);

export interface FileRoutesByFullPath {
	"/": typeof IndexRoute;
	"/waitlist": typeof WaitlistRoute;
	"/callback": typeof authCallbackRoute;
	"/login": typeof authLoginRoute;
	"/register": typeof authRegisterRoute;
	"/onboarding/$slug": typeof OnboardingSlugRoute;
	"/problems/$problem-slug": typeof ProblemsProblemSlugRoute;
	"/problems": typeof ProblemsLayoutRouteWithChildren;
	"/problems/layout": typeof ProblemsLayoutRoute;
	"/onboarding": typeof OnboardingIndexRoute;
	"/problems/": typeof ProblemsLayoutIndexRoute;
}

export interface FileRoutesByTo {
	"/": typeof IndexRoute;
	"/waitlist": typeof WaitlistRoute;
	"/callback": typeof authCallbackRoute;
	"/login": typeof authLoginRoute;
	"/register": typeof authRegisterRoute;
	"/onboarding/$slug": typeof OnboardingSlugRoute;
	"/problems/$problem-slug": typeof ProblemsProblemSlugRoute;
	"/problems/layout": typeof ProblemsLayoutRoute;
	"/onboarding": typeof OnboardingIndexRoute;
	"/problems": typeof ProblemsLayoutIndexRoute;
}

export interface FileRoutesById {
	__root__: typeof rootRoute;
	"/": typeof IndexRoute;
	"/waitlist": typeof WaitlistRoute;
	"/callback": typeof authCallbackRoute;
	"/login": typeof authLoginRoute;
	"/register": typeof authRegisterRoute;
	"/onboarding/$slug": typeof OnboardingSlugRoute;
	"/problems/$problem-slug": typeof ProblemsProblemSlugRoute;
	"/problems": typeof ProblemsRouteWithChildren;
	"/problems/_layout": typeof ProblemsLayoutRouteWithChildren;
	"/problems/layout": typeof ProblemsLayoutRoute;
	"/onboarding/": typeof OnboardingIndexRoute;
	"/problems/": typeof ProblemsIndexRoute;
	"/problems/_layout/": typeof ProblemsLayoutIndexRoute;
}

export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath;
	fullPaths:
		| "/"
		| "/waitlist"
		| "/callback"
		| "/login"
		| "/register"
		| "/onboarding/$slug"
		| "/problems/$problem-slug"
		| "/problems"
		| "/problems/layout"
		| "/onboarding"
		| "/problems/";
	fileRoutesByTo: FileRoutesByTo;
	to:
		| "/"
		| "/waitlist"
		| "/callback"
		| "/login"
		| "/register"
		| "/onboarding/$slug"
		| "/problems/$problem-slug"
		| "/problems/layout"
		| "/onboarding"
		| "/problems";
	id:
		| "__root__"
		| "/"
		| "/waitlist"
		| "/callback"
		| "/login"
		| "/register"
		| "/onboarding/$slug"
		| "/problems/$problem-slug"
		| "/problems"
		| "/problems/_layout"
		| "/problems/layout"
		| "/onboarding/"
		| "/problems/"
		| "/problems/_layout/";
	fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
	IndexRoute: typeof IndexRoute;
	WaitlistRoute: typeof WaitlistRoute;
	authCallbackRoute: typeof authCallbackRoute;
	authLoginRoute: typeof authLoginRoute;
	authRegisterRoute: typeof authRegisterRoute;
	OnboardingSlugRoute: typeof OnboardingSlugRoute;
	ProblemsProblemSlugRoute: typeof ProblemsProblemSlugRoute;
	ProblemsRoute: typeof ProblemsRouteWithChildren;
	OnboardingIndexRoute: typeof OnboardingIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
	IndexRoute: IndexRoute,
	WaitlistRoute: WaitlistRoute,
	authCallbackRoute: authCallbackRoute,
	authLoginRoute: authLoginRoute,
	authRegisterRoute: authRegisterRoute,
	OnboardingSlugRoute: OnboardingSlugRoute,
	ProblemsProblemSlugRoute: ProblemsProblemSlugRoute,
	ProblemsRoute: ProblemsRouteWithChildren,
	OnboardingIndexRoute: OnboardingIndexRoute,
};

export const routeTree = rootRoute
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>();

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/waitlist",
        "/callback",
        "/login",
        "/register",
        "/onboarding/$slug",
        "/problems/$problem-slug",
        "/problems",
        "/onboarding/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/waitlist": {
      "filePath": "waitlist.tsx"
    },
    "/callback": {
      "filePath": "(auth)/callback.tsx"
    },
    "/login": {
      "filePath": "(auth)/login.tsx"
    },
    "/register": {
      "filePath": "(auth)/register.tsx"
    },
    "/onboarding/$slug": {
      "filePath": "onboarding/$slug.tsx"
    },
    "/problems/$problem-slug": {
      "filePath": "problems/$problem-slug.tsx"
    },
    "/problems": {
      "filePath": "problems",
      "children": [
        "/problems/_layout",
        "/problems/layout",
        "/problems/"
      ]
    },
    "/problems/_layout": {
      "filePath": "problems/_layout.tsx",
      "parent": "/problems",
      "children": [
        "/problems/_layout/"
      ]
    },
    "/problems/layout": {
      "filePath": "problems/layout.tsx",
      "parent": "/problems"
    },
    "/onboarding/": {
      "filePath": "onboarding/index.tsx"
    },
    "/problems/": {
      "filePath": "problems/index.tsx",
      "parent": "/problems"
    },
    "/problems/_layout/": {
      "filePath": "problems/_layout.index.tsx",
      "parent": "/problems/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
